AEDB-25 list of aggregated demand per course
SkillsFundingAgency/das-employerdemand-api pull request #5
Opened 2021-03-29 19:14 UTC by scottywakefield

2021-03-30 08:09 UTC, dashton82 requested changes

2021-03-30 08:09 UTC, dashton82 commented on src/SFA.DAS.EmployerDemand.Api/ApiModels/GetAggregatedCourseDemandListResponse.cs
> +namespace SFA.DAS.EmployerDemand.Api.ApiModels
do we not normally call these `ApiResponses`?

2021-03-30 08:09 UTC, dashton82 commented on src/SFA.DAS.EmployerDemand.Api/Controllers/DemandController.cs
> +        public async Task<IActionResult> GetAggregatedCourseDemandList()
Seeing that this will need to accept the `ukprn` we could probably change the name of the action/route to reflect that

2021-03-30 08:09 UTC, dashton82 commented on src/SFA.DAS.EmployerDemand.Application/CourseDemand/Services/CourseDemandService.cs.orig
> +using System.Collections.Generic;
Can add this to the ignore file 😄

2021-03-30 08:09 UTC, dashton82 commented on src/SFA.DAS.EmployerDemand.Data/Repository/CourseDemandRepository.cs.orig
> +using System.Collections.Generic;
gitignore addition

2021-03-30 13:31 UTC, dashton82 approved these changes

2021-04-09 08:37 UTC, scottywakefield reviewed
all good

2021-04-09 08:50 UTC, dashton82 approved these changes

2021-04-09 12:11 UTC, merged